### ISSUE TITLE
Duplicate registry on Data Evaluator dropdown list (USI)

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/wp5-demo-ui#20]
Once you select the Data Evaluator inside the USI Exchange (User), the following participants hold the same information:
* (JSI) Institut Jozef Stefan
* (MIZS) Ministrstvo za Izobrazevanje, Znanost in Sport (Ministry of Education, Science and Sport)

The correct correspondence should be:
* (JSI) Institut Jozef Stefan -> `iso6523-actorid-upis::9999:si000000018`
* (MIZS) Ministrstvo za Izobrazevanje, Znanost in Sport (Ministry of Education, Science and Sport) -> `iso6523-actorid-upis::9999:si000000016`

**Comment by phax** [comment]
Yes I know - because for one them no SMP entry exists.... But I will revert it back

**Comment by aosunacab** [comment]
But if it is needed, we shoudl create the registry on the SMP.
